/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          container: "var(--primary-container)",
          "container-foreground": "var(--on-primary-container)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
          container: "var(--secondary-container)",
          "container-foreground": "var(--on-secondary-container)",
        },
        tertiary: {
          DEFAULT: "var(--tertiary)",
          foreground: "var(--tertiary-foreground)",
          container: "var(--tertiary-container)",
          "container-foreground": "var(--on-tertiary-container)",
        },
        destructive: {
          DEFAULT: "var(--error)",
          foreground: "var(--on-error)",
          container: "var(--error-container)",
          "container-foreground": "var(--on-error-container)",
        },
        muted: {
          DEFAULT: "var(--surface-variant)",
          foreground: "var(--on-surface-variant)",
        },
        accent: {
          DEFAULT: "var(--surface-variant)",
          foreground: "var(--on-surface-variant)",
        },
        popover: {
          DEFAULT: "var(--surface)",
          foreground: "var(--on-surface)",
        },
        card: {
          DEFAULT: "var(--surface)",
          foreground: "var(--on-surface)",
        },
        surface: {
          DEFAULT: "var(--surface)",
          dim: "var(--surface-dim)",
          bright: "var(--surface-bright)",
          "container-lowest": "var(--surface-container-lowest)",
          "container-low": "var(--surface-container-low)",
          container: "var(--surface-container)",
          "container-high": "var(--surface-container-high)",
          "container-highest": "var(--surface-container-highest)",
          foreground: "var(--on-surface)",
          variant: "var(--surface-variant)",
          "variant-foreground": "var(--on-surface-variant)",
          inverse: "var(--inverse-surface)",
          "inverse-foreground": "var(--inverse-on-surface)",
          tint: "var(--surface-tint)",
        },
        outline: {
          DEFAULT: "var(--outline)",
          variant: "var(--outline-variant)",
        },
        midnight: "#0B132B",
        navy: "#1C2541",
        navyLight: "#2B375E",
        sapphire: "#1D4ED8",
        cerulean: "#2563EB",
        ceruleanBright: "#3B82F6",
        porcelain: "#F8FAFC",
        slateBorder: "#E2E8F0",
        slateText: "#475569",
        slateLight: "#F1F5F9",
        danger: "#DC2626",
        dangerBg: "#FEF2F2",
        dangerBorder: "#FCA5A5",
      },
      borderRadius: {
        lg: "0.5rem",
        md: "calc(0.5rem - 2px)",
        sm: "calc(0.5rem - 4px)",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        headline: ["'Space Grotesk'", "sans-serif"],
        data: ["'JetBrains Mono'", "monospace"],
      },
    },
  },
  plugins: [],
}
